apiVersion: v2
appVersion: "v2.10.0"
description: Cloud Native storage for containers
name: ondat-operator
version: 0.7.4
keywords:
- storage
- block-storage
- volume
- operator
home: https://ondat.io
icon: https://docs.ondat.io/images/generic/Ondat_logo.svg
sources:
- https://github.com/ondat
maintainers:
- name: DavidMarchant
  email: david@ondat.io
- name:  mhmxs
  email: richard.kovacs@ondat.io
- name: scflavell
  email: simon.flavell@ondat.io
