apiVersion: v1
data:
  operator_config.yaml: |
    apiVersion: config.storageos.com/v1
    kind: OperatorConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: storageos-operator
    webhookCertRefreshInterval: 15m
    webhookServiceName: storageos-operator-webhook
    webhookSecretRef: storageos-operator-webhook
    validatingWebhookConfigRef: storageos-operator-validating-webhook
kind: ConfigMap
metadata:
  labels:
    app: {{ template "storageos.name" . }}
    app.kubernetes.io/component: operator
    chart: {{ template "storageos.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: storageos-operator
  namespace: {{ .Release.Namespace }}
---

apiVersion: v1
data:
  {{- if and .Values.global.azure.images.apiManager.image .Values.global.azure.images.apiManager.digest }}
  RELATED_IMAGE_API_MANAGER: "{{ .Values.global.azure.images.apiManager.registry}}/{{ .Values.global.azure.images.apiManager.image }}@{{ .Values.global.azure.images.apiManager.digest }}"
  {{- end }}
  {{- if and .Values.global.azure.images.csiV1ExternalAttacherV3.image .Values.global.azure.images.csiV1ExternalAttacherV3.digest }}
  RELATED_IMAGE_CSIV1_EXTERNAL_ATTACHER_V3: "{{ .Values.global.azure.images.csiV1ExternalAttacherV3.registry}}/{{ .Values.global.azure.images.csiV1ExternalAttacherV3.image }}@{{ .Values.global.azure.images.csiV1ExternalAttacherV3.digest }}"
  {{- end }}
  {{- if and .Values.global.azure.images.csiV1ExternalProvisioner.image .Values.global.azure.images.csiV1ExternalProvisioner.digest }}
  RELATED_IMAGE_CSIV1_EXTERNAL_PROVISIONER: "{{ .Values.global.azure.images.csiV1ExternalProvisioner.registry}}/{{ .Values.global.azure.images.csiV1ExternalProvisioner.image }}@{{ .Values.global.azure.images.csiV1ExternalProvisioner.digest }}"
  {{- end }}
  {{- if and .Values.global.azure.images.csiV1ExternalResizer.image .Values.global.azure.images.csiV1ExternalResizer.digest }}
  RELATED_IMAGE_CSIV1_EXTERNAL_RESIZER: "{{ .Values.global.azure.images.csiV1ExternalResizer.registry}}/{{ .Values.global.azure.images.csiV1ExternalResizer.image }}@{{ .Values.global.azure.images.csiV1ExternalResizer.digest }}"
  {{- end }}
  {{- if and .Values.global.azure.images.csiV1ExternalSnapshotter.image .Values.global.azure.images.csiV1ExternalSnapshotter.digest }}
  RELATED_IMAGE_CSIV1_EXTERNAL_SNAPSHOTTER: "{{ .Values.global.azure.images.csiV1ExternalSnapshotter.registry}}/{{ .Values.global.azure.images.csiV1ExternalSnapshotter.image }}@{{ .Values.global.azure.images.csiV1ExternalSnapshotter.digest }}"
  {{- end }}
  {{- if and .Values.global.azure.images.csiV1LivenessProbe.image .Values.global.azure.images.csiV1LivenessProbe.digest }}
  RELATED_IMAGE_CSIV1_LIVENESS_PROBE: "{{ .Values.global.azure.images.csiV1LivenessProbe.registry}}/{{ .Values.global.azure.images.csiV1LivenessProbe.image }}@{{ .Values.global.azure.images.csiV1LivenessProbe.digest }}"
  {{- end }}
  {{- if and .Values.global.azure.images.csiV1NodeDriverRegistrar.image .Values.global.azure.images.csiV1NodeDriverRegistrar.digest }}
  RELATED_IMAGE_CSIV1_NODE_DRIVER_REGISTRAR: "{{ .Values.global.azure.images.csiV1NodeDriverRegistrar.registry}}/{{ .Values.global.azure.images.csiV1NodeDriverRegistrar.image }}@{{ .Values.global.azure.images.csiV1NodeDriverRegistrar.digest }}"
  {{- end }}
  {{- if and .Values.global.azure.images.metricsExporter.image .Values.global.azure.images.metricsExporter.digest }}
  RELATED_IMAGE_METRICS_EXPORTER: "{{ .Values.global.azure.images.metricsExporter.registry}}/{{ .Values.global.azure.images.metricsExporter.image }}@{{ .Values.global.azure.images.metricsExporter.digest }}"
  {{- end }}
  {{- if and .Values.global.azure.images.nodeManager.image .Values.global.azure.images.nodeManager.digest }}
  RELATED_IMAGE_NODE_MANAGER: "{{ .Values.global.azure.images.nodeManager.registry}}/{{ .Values.global.azure.images.nodeManager.image }}@{{ .Values.global.azure.images.nodeManager.digest }}"
  {{- end }}
  {{- if and .Values.global.azure.images.portalManager.image .Values.global.azure.images.portalManager.digest }}
  RELATED_IMAGE_PORTAL_MANAGER: "{{ .Values.global.azure.images.portalManager.registry}}/{{ .Values.global.azure.images.portalManager.image }}@{{ .Values.global.azure.images.portalManager.digest }}"
  {{- end }}
  {{- if and .Values.global.azure.images.init.image .Values.global.azure.images.init.digest }}
  RELATED_IMAGE_STORAGEOS_INIT: "{{ .Values.global.azure.images.init.registry}}/{{ .Values.global.azure.images.init.image }}@{{ .Values.global.azure.images.init.digest }}"
  {{- end }}
  {{- if and .Values.global.azure.images.node.image .Values.global.azure.images.node.digest }}
  RELATED_IMAGE_STORAGEOS_NODE: "{{ .Values.global.azure.images.node.registry}}/{{ .Values.global.azure.images.node.image }}@{{ .Values.global.azure.images.node.digest }}"
  {{- end }}
  {{- if and .Values.global.azure.images.nodeGuard.image .Values.global.azure.images.nodeGuard.digest }}
  RELATED_IMAGE_NODE_GUARD: "{{ .Values.global.azure.images.nodeGuard.registry}}/{{ .Values.global.azure.images.nodeGuard.image }}@{{ .Values.global.azure.images.nodeGuard.digest }}"
  {{- end }}
kind: ConfigMap
metadata:
  labels:
    app: {{ template "storageos.name" . }}
    app.kubernetes.io/component: operator
    chart: {{ template "storageos.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: storageos-related-images
  namespace: {{ .Release.Namespace }}
---

apiVersion: v1
data:
  portal_config.yaml: |
    apiVersion: storageos.com/v1alpha1
    kind: PortalConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceNamespace: storageos
      resourceName: storageos-portal-manager
kind: ConfigMap
metadata:
  labels:
    app: {{ template "storageos.name" . }}
    app.kubernetes.io/component: portal-manager
  name: storageos-portal-manager
  namespace: {{ template "cluster.namespace" . }}
