---
apiVersion: apps/v1
kind: Deployment
metadata:
{{- template "etcd-cluster-operator.labels" . }}
    control-plane: etcd-controller-manager
  name: storageos-etcd-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      control-plane: etcd-controller-manager
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        control-plane: etcd-controller-manager
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  control-plane: etcd-controller-manager
              topologyKey: kubernetes.io/hostname
      containers:
        - args:
            - --enable-leader-election
            - --proxy-url=storageos-proxy.{{ .Release.Namespace }}.svc
            - --leader-election-cm-namespace={{ .Release.Namespace }}
            - --etcd-repository={{ .Values.global.azure.images.etcd.registry }}/{{ .Values.global.azure.images.etcd.image }}
          command:
            - /manager
          env:
            - name: DISABLE_WEBHOOKS
              value: "true"
          image: {{ .Values.global.azure.images.etcdClusterOperatorController.registry}}/{{ .Values.global.azure.images.etcdClusterOperatorController.image}}@{{ .Values.global.azure.images.etcdClusterOperatorController.digest }}
          name: manager
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 120Mi
      terminationGracePeriodSeconds: 10
